version: '3'

volumes:
  onlyoffice-logs:
  onlyoffice-data:

services:
   onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    restart: always
    ports:
      - 7070:80
    volumes:
      - onlyoffice-data:/var/www/onlyoffice/Data:rw
      - onlyoffice-logs:/var/log/onlyoffice
