version: '3'

volumes:
  nextcloud:
  redis:

services:
  mariadb:
    image: mariadb
    container_name: mariadb-nextcloud
    restart: always
    ports:
      - '32568:3306'
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    container_name: redis-nextcloud
    restart: unless-stopped
    command: redis-server --requirepass q9Sx807VEaR5UqUw9VCp
    volumes:
      - redis:/data

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    depends_on:
      - redis
      - mariadb
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - .env
