version: '3'

volumes:
  letsencrypt:

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    env_file:
      - .env
    volumes:
      - ./data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-db

  npm-db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
